observablehq/framework

.github/workflows/deploy.yml
~~TODO Apply the same technique to the examples. Currently this only caches the top-level project data loaders.~~ Done.
=> cache data

src/deploy.ts
Following up on https://github.com/observablehq/framework/pull/790#discussion_r1490195836.  
_"...instead of filtering in we should filter out the workspaces that we know don’t allow projects"._
=> Filtering out invalid tiers instead of filtering in.

docs/loaders.md
Added the missing `quake.csv.go` entry to the list of data loaders.
=> quakes.csv.go was left out of the data loaders list

src/client/search.js, src/search.ts
- add the home page to the default list of indexable pages
- even though it's not in pages, it's not ‘unlisted’
- one can still opt out with index: false, as we do for this documentation
closes #815
- support empty titles (replaced with a emdash), and titles such as numbers
you can test this by adding this to a listed and indexed page:
```
---
title: 3.141592
---
```
then if you searched for "happi" you would see the client error in the console (and no result was displayed) as it was trying to apply the escaping code to a Number.
=> bug fixes for search

bin/observable.ts, test/preview/preview-test.ts
Ref. https://github.com/observablehq/framework/issues/90#issuecomment-1950294898
=> no process.env.{HOSTNAME,PORT}

docs/getting-started.md
=> fix implicit display documentation

src/observableApiAuth.ts, test/observableApiAuth-test.ts
We might also be able to do this by having timeouts be an effect instead of using a short timeout, but this seems like an easier way to deal with it.
=> make login test faster by not waiting 1s to poll

docs/config.md, examples/api/observablehq.config.ts, examples/chess/observablehq.config.ts, examples/eia/observablehq.config.ts, examples/google-analytics/observablehq.config.ts, examples/hello-world/observablehq.config.ts, examples/mortgage-rates/observablehq.config.ts, examples/penguin-classification/observablehq.config.ts, examples/plot/observablehq.config.ts, observablehq.config.ts
Followup to #921. Using **head** is simpler (and we already do that for Google Analytics). Adds documentation for the **scripts** option, too.
=> document scripts; use head

src/libraries.ts, src/npm.ts
Some of these would be statically discoverable by parsing the CSS, but some of them are only referenced in the code (and without using `import.meta.resolve`), so we’ll need to enumerate these anyway if we want it to work out of the box.
=> add leaflet images

src/client/stdlib/fileAttachment.js, src/preview.ts, src/render.ts
Fixes #874. I thought about just fixing this to null, and then I thought making it undefined, but then I figured we can reasonably assume what the default MIME type will be of the server in this case (application/octet-stream), so we might as well use that and then users don’t need to handle this field being unavailable.
=> default mimeType to application/octet-stream

src/style/global.css
It just looks better in general.
example:
=> adopt text-wrap: balance for all headers

docs/markdown.md
very minimalist documentation; should we mention that **keywords** weight as much as **title**? Do we want to add a version badge?
=> document keywords

src/preview.ts
While running Framework with a Markdown file with spaces in its name (`Test File.md`), I encountered:
```
Protocol error Error: ENOENT: no such file or directory, open 'Test%20File.md'
at open (node:internal/fs/promises:633:25)
at readFile (node:internal/fs/promises:1242:14)
at parseMarkdown (file:///Users/huw/Library/Mobile Documents/iCloud~md~obsidian/Documents/node_modules/.pnpm/@observablehq+framework@1.0.0_@types+markdown-it@13.0.7/node_modules/@observablehq/framework/src/markdown.ts:421:18)
at hello (file:///Users/huw/Library/Mobile Documents/iCloud~md~obsidian/Documents/node_modules/.pnpm/@observablehq+framework@1.0.0_@types+markdown-it@13.0.7/node_modules/@observablehq/framework/src/preview.ts:373:15)
at WebSocket.<anonymous> (file:///Users/huw/Library/Mobile …
```
=> Decode Markdown filename URIs in preview (allow spaces)

src/build.ts, src/rollup.ts
it's only a 10% gain when we compare the gzip'd payloads, and we'd need a sourcemap?
not urgent in any case
=> minify css

.github/workflows/deploy.yml, docs/contributing.md, docs/telemetry.md, package.json
Per https://github.com/observablehq/framework/pull/963#issuecomment-1976110292, and to fix the examples build, which needs both `yarn docs:build` to build the docs, and `yarn build` so that the examples can run `build/bin/observable.js`.
=> separate docs:build

src/create.ts
Running a bare `observable create` currently defaults to not installing dependencies, which is not recommended. This changes the default to npm instead.
=> default to npm

docs/getting-started.md, package.json, src/create.ts
yarn dlx needs an empty yarn.lock to indicate that it’s a new project, or it gets confused.
=> fix yarn dlx

src/build.ts, src/config.ts, src/markdown.ts, src/preview.ts, src/resolvers.ts, src/search.ts, test/markdown-test.ts, test/resolvers-test.ts
There was a bug where a transitive static import from a dynamic import was considered a static import, but it should be considered a dynamic import. Adds more tests for `getResolvers` to increase coverage.
=> fix transitive static imports

docs/lib/echarts.md, src/client/stdlib/recommendedLibraries.js, src/libraries.ts, src/npm.ts, test/mocks/jsdelivr.ts
Seems like the latest version works, as long as you use the correct entry (`dist/echarts.esm.min.js`).
=> unpin echarts

src/client/stdlib/fileAttachment.js, test/client/stdlib/fileAttachment-test.ts
Fixes #989. The file name is resolved against `import.meta.url`, but the file path is resolved against the serving page. I’ll see if I can write some tests for this. (We don’t have many tests yet for client-side code.)
=> fix FileAttachment resolution in imports

docs/loaders.md
it's possible that the example code might be too much or too convoluted… we can edit it down if it's not salvageable, and do a real-life complete example instead
closes #853
=> document data loaders' cwd and import.meta.url

src/client/main.js
The `display` function now captures the current version whenever the inputs (other than `display` and `view`) change, such that when a variable is invalidated, it gets a new `display` function capturing the new version. And, we now throw an error if `display` is called with a version that is older than the last-displayed content. Users should never see this error (unless they use developer tools to break on caught exceptions), but it also prevents downstream work for a variable that has been invalidated, which is nice.
I had to reach into the Runtime internals to get this to work, because I wanted shadow variables that depend on other variables. (Normally shadow variables aren’t allowed to have any inputs, but it’s really just a limitation of the **shadow** option, not the underlying …
=> fix stale display

src/resolvers.ts
=> fix live update of front matter

docs/lib/mosaic.md, docs/lib/nyc-taxi.parquet.sh, observablehq.config.ts
=> document Mosaic

src/npm.ts, test/javascript/npm-test.ts, test/mocks/jsdelivr.ts
Fixes #1019. Rather than relying on the versions baked-in to jsDelivr, we now download the `package.json` and re-resolve the versions of transitive dependencies. This ensures that you get consistent versions, when possible, of transitive dependencies. In addition, we override @uwdata/mosaic-core’s dependencies on @duckdb/duckdb-wasm and apache-arrow to match Framework’s pinned versions.
Loading the `package.json` is a bit slow, but I can’t think of a faster way to do this. Perhaps we could have an `observable install` command that you can run from the command-line to populate the npm cache for all known pages. We could then run that command as part of `observable create` so you don’t experience slow page loads.
=> re-resolve npm imports; apache-arrow 15

src/deploy.ts, src/observableApiClient.ts, test/deploy-test.ts, test/mocks/observableApi.ts
Resolves https://github.com/observablehq/framework/issues/879
The Observable API postProject endpoint already supports an access level (private/public), so expose that as a selection during project creation. Defaults to private.
Looks like:
```
│
◆  Who is allowed to access your project?
│  ● Private (only allow workspace members)
│  ○ Public
└
```
```
│
◆  Who is allowed to access your project?
│  ○ Private
│  ● Public (allow anyone)
└
```
=> Prompt for access level during project creation.

src/config.ts, src/markdown.ts, src/search.ts, test/config-test.ts, test/markdown-test.ts, test/resolvers-test.ts
A bit of refactoring before addressing #92, and maybe reviving #702.
=> centralize md instance as part of the normalized configuration

docs/deploying.md, docs/getting-started.md, observablehq.config.ts
This replaces the link in getting-started to Framework's deploy.yml with link to a dedicated deploy documentation page. This page has a simpler example configuration for GitHub Actions, as well as documenting the `OBVSERVABLE_TOKEN` environment variable.
There is some amount of duplication between this new page and the getting-started page, but I think that's ok.
=> add docs for automatic deploys, with github actions example

src/html.ts, src/javascript/imports.ts, src/markdown.ts, src/path.ts, src/preview.ts, src/render.ts, src/resolvers.ts, test/html-test.ts, test/input/build/imports/script.md, test/output/build/imports/foo/foo.html, test/output/build/imports/script.html
For JavaScript scripts (see [script[type]](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#type)), the `src` attribute is resolved as an import; for non-JavaScript scripts, it is resolved as a file. This means you can now load vanilla JavaScript scripts (or modules), and it “just works”. For module scripts, the module is also preloaded.
=> resolve script[src]

src/client/stdlib/duckdb.js
These methods broke because `db.query` now returns an Arrow table rather than an Array, and hence has no _array_.map method. (We’ve deviated from the DatabaseClient specification now, but that’s a good thing because Arrow tables are much, much faster.)
````md
```js echo
const arrowTable = Arrow.tableFromArrays({col1: [1, 2, 3], col2: ["one", "two", "three"]});
const db = await DuckDBClient.of({arrowTable});
```
```js echo
db.describeTables()
```
```js echo
db.query("SELECT * FROM arrowTable")
```
````
=> fix describe{Tables,Columns}

docs/config.md
=> document pages

src/config.ts, src/markdown.ts, src/path.ts, test/config-test.ts, test/markdown-test.ts, test/path-test.ts
Fixes #1110. Ref. #1100. Preserves query strings, anchor fragment, and absolute URLs; drops trailing `.html` from the path; adds leading slash (`/`) if needed; adds trailing `/index` if needed.
=> normalize pages

src/client/stdlib/mermaid.js
Alternative to #1115. Still requires a reload if you change your preferred color scheme, but I think that’s okay.
=> fix mermaid dark theme

docs/deploying.md
=> hint to "deploy help" in the documentation

src/client/stdlib/fileAttachment.js
Fixes a regression in #1113: we can’t rely on `file.href` existing in the case of `ZipArchiveEntry`.
=> fix ZipArchiveEntry

src/html.ts
A `<script type="module" async>` probably shouldn’t be preloaded — the [`async` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#async) implies that it’s lower priority. For example, we don’t want to preload our first-party analytics script on the Framework documentation.
=> don’t preload async

docs/style.css, observablehq.config.ts, package.json, yarn.lock
=> show GitHub stars in header

src/preview.ts
The lazy config #695 introduced a race condition where we could drop a _hello_↑ message that is sent immediately upon connection because we were waiting for the config to load. Now we register the _message_ event listener (and other listeners) synchronously on connect, moving the await to within the listener. Fixes #563.
=> fix hello race condition

docs/getting-started.md, src/create.ts
Fixes #1134. We don’t want to show the `./` on Windows, and we don’t need it on POSIX, so we might as well remove it.
=> no ./ for default path

docs/index.md
I think this was useful in earlier iterations, but since this page not "fullwidth" anymore, the only effect of the toc option on [the home page](https://observablehq.com/framework) now is to move the github link to the right; probably better to be consistent with other pages like https://observablehq.com/framework/css/note
| --- | --- |
| ![before](https://github.com/observablehq/framework/assets/7001/41ca64ce-b8c5-4251-afb3-4bd0b6aa0397) | ![after](https://github.com/observablehq/framework/assets/7001/fdaf0ded-4be1-4726-ab66-36ac744aca78) |
=> remove toc: false on the home page?

src/create.ts, test/create-test.ts
Fixes #1064. By running build during create, the initial loads of Framework in the preview server are instant because the npm and data loader cache are already populated. I think this is a better user experience — you’re expecting to wait during install anyway, and it means your first experience seeing pages load in Framework is representative of the (instant) experience of the cached and built project.
=> initialize cache on create

src/config.ts, src/preview.ts, test/config-test.ts
Followup to #695 which actively watches the config file and tells the client to *reload*↓ if the config file changes. Might be overkill, and a bit hard to test in this repo since we use `tsx watch`, too. What do you think? Seems fine to me…
=> reload on config change

docs/markdown.md, src/frontMatter.ts, src/markdown.ts, test/frontMatter-test.ts
I noticed that the theme previews erroneously have a head and header again (and so it’s inflating our traffic numbers). It was caused by a regression in #1054 that dropped the **head**, **header**, and **footer** options. These options were also undocumented, but now they are.
=> fix head, header, footer front matter

src/npm.ts, test/npm-test.ts
In the process of documenting imports, I noticed we don’t handle specifying named entry points well. This fixes importing a named entry point such as:
```js
import mime from "npm:mime/lite";
```
Without this, the import would fail because the `.js` extension is needed to set the MIME type correctly, and also because jsDelivr doesn’t support loading a named entry point without `/+esm` ([e.g.](https://cdn.jsdelivr.net/npm/mime@4.0.1/lite)). You could workaround it like so:
```js
import mime from "npm:mime/lite/+esm";
```
But I figure that it would be better if it “just worked” rather than knowing you need to add `/+esm`, just like the default `npm:mime` without a path works.
I also thought about implicitly adding `/+esm` for paths with JavaScript extensions, such as:
```js
import …
```
=> implicit /+esm if no extension; fix /+esm conflict

docs/deploying.md
ObservableHQ recently added support for direct links to workspace pages. It will either prompt the user for the workspace they want to use, or directly navigate to it in the case they only have one workspace.
=> Add direct links to Observable settings in docs

examples/README.md, examples/mortgage-rates/README.md, examples/mortgage-rates/docs/interactive.md, examples/mortgage-rates/observablehq.config.ts
This adds a (simple) interactive version of the PMMS dashboard, as described in this blog post: https://observablehq.com/blog/how-to-add-interactivity-observable-framework-dashboard
=> Add interactive version of PMMS dashboard

docs/lib/csv.md, src/client/stdlib/fileAttachment.js
Adds a `FileAttachment.dsv` method which takes a **delimiter** option, so you’re not limited to CSV/TSV.
=> FileAttachment.dsv

src/npm.ts, test/npm-test.ts
This makes imports such as this work out of the box:
```js
import Deck from "npm:deck.gl/dist.min.js";
```
```js
import mermaid from "npm:mermaid/dist/mermaid.esm.min.mjs";
```
Previously these imports would error because they require `/+esm`; now the `/+esm` is added implicitly so it “just works.”
This also fixes the default entry for deck.gl, so that this now works, too:
```js
import Deck from "npm:deck.gl";
```
(I did see an error once about “multiple versions of luma detected”… but couldn’t reproduce it reliably.)
=> implicit /+esm for JavaScript extensions

docs/javascript/imports.md, src/node.ts, src/rollup.ts
Fixes #1162. Also explicitly sets esbuild’s **format** to _esm_ and **platform** to _browser_, since we don’t want it guessing.
Re. **platform**, it defaults to _browser_ so setting it explicitly should have no effect, but feels like a good idea for our usage.
Re. **format**, my understanding is that if **minify** is set to true then **bundle** is implicitly set to true and **format** defaults to _esm_ (because **platform** is *browser*); however we don’t always set **minify** to true (and I noticed when I turned it off in development) in which case **bundle** defaults to false (and rollup does the bundling) and then esbuild doesn’t do any format conversion so we could end up with CommonJS. 😅
=> more import docs; format=esm platform=browser

src/npm.ts
Fixes #1180, to the best of our abilities. If jsDelivr doesn’t give us a version, as when a module imports an undeclared dependency, we now resolve the latest version.
=> handle undeclared dependencies

src/node.ts, test/node-test.ts
Fixes #1181, to the best of our abilities. You still can’t import deck.gl successfully, though (because deck.gl’s `package.json` doesn’t declare the `dist.min.js` as an export so you’re not allowed to import it, and because the default export `dist/index.js` depends on a variety of modules that esbuild complains about because they use `require` which I’m not sure how to fix).
=> ignore node built-ins

src/bin/observable.ts, src/create.ts, test/create-test.ts
Fixes #1189. Looks like this:
```
◇  Initialize git repository?
│  Yes
│
◇  Installed! 🎉
│
▲  Failed to initialize Framework cache. This may be a transient error loading data
│  from external servers or downloading imported modules from jsDelivr; or it might
│  be a network configuration issue such as a firewall blocking traffic. You can
│  ignore this error for now and Framework will automatically try to download again
│  on preview or build. If you continue to experience network issues, please check
│  your network configuration.
│
│  Want help? https://github.com/observablehq/framework/issues
│
│
◇  Next steps… ────────╮
│                      │
│  cd hello-framework  │
│  yarn dev            │
│                      │
├──────────────────────╯
│
└  Problems? …
```
=> handle build error

examples/api/observablehq.config.ts, examples/chess/observablehq.config.ts, examples/eia/observablehq.config.ts, examples/google-analytics/observablehq.config.ts, examples/hello-world/observablehq.config.ts, examples/mortgage-rates/observablehq.config.ts, examples/penguin-classification/observablehq.config.ts, examples/plot/observablehq.config.ts, observablehq.config.ts
The analytics client script used to always send an automatic pageLoad event for us unless it detected other usage within a certain time period. Instead of the finicky (and race condition prone) time-based method, the latest script uses a request parameter to indicate if it should automatically emit a pageLoad event.
=> Import with auto pageLoad event

docs/config.md, src/config.ts, src/render.ts, src/style/layout.css, test/config-test.ts, test/pager-test.ts
This is progress towards a richer sidebar related to improved docs #1187. I also want to add subsections (three levels of hierarchy). This also fixes a missing `TableOfContents` type declaration; apparently if it’s missing, TypeScript considers it any rather than throwing an error which is surprising and probably a misconfiguration.
It looks like you would expect:
=> non-collapsible sections

docs/imports.md
=> add version badge for node imports

src/bin/observable.ts, src/deploy.ts, src/files.ts, test/deploy-test.ts, test/mocks/observableApi.ts
Fixes #1214
Also introduces --build and --no-build deploy flags. Uses Clack `confirm` where possible, and switches "youngest" / "age" variables to prefer least-recent and most-recent modification time millis.
=> Check most-recent source modification time when deciding to do a build.

docs/getting-started.md, docs/markdown.md, src/convert.ts, src/create.ts, src/deploy.ts, src/observableApiAuth.ts
As we heard from @CAYdenberg in https://github.com/observablehq/framework/pull/1187#discussion_r1561443942, the _Getting started_ tutorial is currently a bit tedious in that it walks you through what are already very clear prompts in the terminal. This truncates the walk-through to provide only a bit of context (_e.g._, “accept the default values”) and the output on success (for confirmation).
I’ve also added a small intro message to the `create` command so that there’s a little more context when you run `npm init @observablehq`, including a link back to the _Getting started_ tutorial:
```
┌   observable create  v1.5.1
│
◆  Welcome to Observable Framework! 👋 This command will help you create a new
│  project. When prompted, you can press Enter to accept the default value.
│
│  Want help? …
```
=> shorter getting started

package.json, src/node.ts, yarn.lock
This fixes an import of the [elliptic](https://github.com/indutny/elliptic) package (and its dependencies). This comes from a [Slack request](https://observable-community.slack.com/archives/C03SEMPUF6F/p1713346102969629) which I debugged. I’ll comment on the changes below.
I tested manually with:
````md
[Elliptic](https://github.com/indutny/elliptic) is an implementation of “fast elliptic curve cryptography in plain JavaScript.”
```js echo
import elliptic from "elliptic";
const {ec: EC} = elliptic;
// Create and initialize EC context
// (better do it once and reuse it)
const ec = new EC("secp256k1");
// Generate keys
const key = ec.genKeyPair();
// Sign the message's hash (input must be an array, or a hex-string)
const msgHash = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
const signature = …
=> fix elliptic import

docs/imports.md
This fixes a minor typo/confusing sentence in the `Remote imports` section of of the imports documentation page. I've made an assumption on what was originally intended, but its a bit unclear as it seems two different thoughts got jumbled into one.
This changes:
`Unlike npm: and node_modules imports, remove imports are not be self-hosted;...`
to 
`Unlike npm: and node_modules imports, remote imports will not be self-hosted;`
=> fix remote imports docs

examples/api/docs/index.md, src/client/stdlib/fileAttachment.js, src/libraries.ts, src/npm.ts, test/libraries-test.ts, test/mocks/jsdelivr.ts
The latest [0.6.0 release of parquet-wasm](https://github.com/kylebarron/parquet-wasm/releases/tag/v0.6.0) fixes the conditional exports so this mostly works out of the box. There’s a slight wrinkle that the default path to the `.wasm` file is incorrect when loaded via the `/+esm` entry point, but we can fix that by passing in the URL to the `.wasm` file explicitly.
Thanks @kylebarron for the fixes!
=> unpin parquet-wasm

src/bin/observable.ts, src/deploy.ts, src/observableApiClient.ts, src/tty.ts, test/deploy-test.ts, test/mocks/clack.ts, test/mocks/observableApi.ts
This changes the deploy command to first upload a manifest of files in the output directory. The manifest contains the path, size, and hash of each file found. The server then sends back instructions to either upload the file, skip it (because it already exists on the server), or an error (such as a file being too large).
The manifest process is mostly invisible to the user. The upload spinner briefly shows that it is preparing a manifest, and the final total shows files that were skipped because they already exist.
I added a new pair of flags, `--manifest` and `--no-manifest`, which use the new and old upload strategies, respectively. The default is to use manifests. My thinking here was that we should merge this PR with the flag, and validate it in CI for a few days. If there is a …
=> use file manifests during uploads

src/deploy.ts, test/deploy-test.ts
Before:
After, if the source files have changed since build:
After, if the source files haven’t changed since build:
=> tidier build prompt

package.json, src/build.ts, src/dataloader.ts, src/format.ts, src/tree.ts, test/format-test.ts, test/markdown-test.ts, test/tree-test.ts, yarn.lock
Fixes #1243. Supersedes #320.
I find it a little hard to read the outputs since the number of fractional digits changes even within units, and the decimal points aren’t aligned. So, I’d like to make that a bit better. I’m also not counting stylesheets, but those should probably be counted too? And is it confusing that “imports” only refers to JavaScript (when you can also import CSS)?
=> page stats

src/deploy.ts
See https://github.com/observablehq/framework/issues/718; one of the files might have enough details already.
In the case of a large file, this changes:
```
◐  Sending file manifest to server│
■  The server rejected some files from the upload:
│
│    - _file/bigfile.60fafc9d.mp4 - (File size of 984 MB exceeds maximum of 50.0 MB)
│
■  Error: Server rejected deploy manifest: no details
```
to 
```
◐  Sending file manifest to server│
■  The server rejected some files from the upload:
│
│    - _file/bigfile.60fafc9d.mp4 - (File size of 984 MB exceeds maximum of 50.0 MB)
│
■  Error: Server rejected deploy manifest
```
=> don't explicitly write "no detail" when there is no instructions.detail

src/tree.ts, test/tree-test.ts
Produces a more compact display when a folder contains only a single page. Redacted example:
```
┌ (7 pages)                       Page      Imports        Files
├── ███████ (4 pages)
│   ├── ██████████/index         32 kB       587 kB     4.794 MB
│   ├── ██████████/index         24 kB       577 kB     1.736 MB
│   ├── ██████████/index         30 kB       587 kB        76 kB
│   └── ██████████/index         24 kB       584 kB       970 kB
├── ███                          16 kB       790 kB    12.522 MB
├── █████████                    32 kB       614 kB       997 kB
└── ██████                       31 kB       610 kB       634 kB
```
=> collapse only child

docs/config.md, src/config.ts
I could not find how to inform the user with typescript, since we don't surface types that would be usable in the configuration file.
closes #1272
=> deprecate the scripts config option

src/client/main.js, src/markdown.ts, src/style/inspector.css, test/output/block-expression.html, test/output/build/archives.posix/tar.html, test/output/build/archives.posix/zip.html, test/output/build/archives.win32/tar.html, test/output/build/archives.win32/zip.html, test/output/build/files/files.html, test/output/build/files/subsection/subfiles.html, test/output/build/missing-file/index.html, test/output/build/missing-import/index.html, test/output/build/multi/index.html, test/output/dollar-expression.html, test/output/dot-graphviz.html, test/output/double-quote-expression.html, test/output/embedded-expression.html, test/output/heading-expression.html, test/output/inline-expression.html, test/output/local-fetch.html, test/output/mermaid.html, test/output/single-quote-expression.html, test/output/template-expression.html, test/output/tex-block.html, test/output/tex-expression.html
Fixes #1299. Removing the DOM element seems to avoid the bug where Safari doesn’t detect that the `:before` pseudoelement should be removed. (There are other workarounds, but this one seems to be probably the cleanest alternative approach without having to do a Safari-specific kludge.)
=> workaround Safari loading bug

src/preview.ts
Fixes a bug where 
```html
<link rel="stylesheet" type="text/css" href="test.css">
```
wouldn’t update when you edit `test.css`. Now it does.
=> watch assets, too

.github/workflows/deploy.yml
No idea if this will actually work until we test it in CI, but I think we should probably be using [setup-python](https://github.com/actions/setup-python?tab=readme-ov-file) to use Python in GitHub Actions. I believe this will enable better caching and be more representative of how users should do it, too.
=> use actions/setup-python

package.json, test/node-test.ts, yarn.lock
Fixes #1330. Supersedes #1331.
=> downgrade jsdom to avoid nwsapi

docs/config.md, src/config.ts, src/markdown.ts, test/input/build/fragments/index.md, test/input/build/fragments/observablehq.config.js, test/output/build/fragments/index.html
head, header and footer can be specified as a function that receives the page’s meta data (path, title and normalized front matter), and returns an HTML fragment (string).
closes #56
Partially addresses #1036, but I'm not sure how we can (or if we should) expose the meta data more generally:
* to the page renderer, so that we could pass the values to be rendered SSR ([#931](https://github.com/observablehq/framework/issues/931)); probably in post-processing?
* to the page runtime (via a `define("meta", …)`)?
Partially addresses #1161.
=> head, header and footer can be specified as a function

src/markdown.ts
Doesn’t make a practical difference (at least not yet — we treat null and the empty string the same during render even though we distinguish these two types), but maintains the pedantic distinction between the empty string and null.
=> more precise null coalescing

src/config.ts
`pager: false` was getting coerced to `pager: null` (correctly), but then the null was coalesced to `"main"` incorrectly. We only want to replace undefined with `"main"`. Needs tests ideally, but I’m rushing.
=> fix pager: null

docs/getting-started.md, src/preview.ts
* review port documentation
* add EACCES as an acceptable error to continue port hopping
* avoid out of memory error if no registered port is reachable, and throw an explicit error instead
closes #1355
=> review port documentation; add EACCES as an acceptable error 

docs/getting-started.md, src/create.ts, templates/default/README.md.tmpl, templates/default/src/index.md.tmpl, templates/empty/README.md.tmpl, templates/empty/src/index.md.tmpl
Rather than always using “Hello, Observable Framework”, use the project title as the hero text on the main page.
=> use project title for hero

test/build-test.ts
we want to remove `skip.` only as a file name prefix
=> fix test name regexp

docs/lib/arrow.md
refs:
- https://talk.observablehq.com/t/date-values/9294
- https://github.com/apache/arrow/pull/40960
=> adopt and document the new apache-arrow date encoding

docs/config.md, src/config.ts, src/pager.ts, src/render.ts, src/search.ts, src/style/layout.css, test/config-test.ts, test/input/build/pager/observablehq.config.js, test/output/build/config/closed/page.html, test/output/build/config/index.html, test/output/build/config/one.html, test/output/build/config/sub/two.html, test/output/build/config/toc-override.html, test/output/build/config/toc.html, test/output/build/pager/index.html, test/output/build/pager/sub/index.html, test/output/build/pager/sub/page0.html, test/output/build/pager/sub/page1..10.html, test/output/build/pager/sub/page1.html, test/output/build/pager/sub/page2.html, test/output/build/pager/sub/page3.html, test/output/build/pager/sub/page4.html, test/output/build/pager/sub/page5.html, test/output/build/pager/sub/page6.html, test/output/build/pager/sub/page7.html, test/output/build/pager/sub/page8.html, test/pager-test.ts
Fixes a bug where the sidebar wouldn’t render correctly if there were only top-level sections and not any top-level pages.
Before:
After:
=> fix sidebar when no top-level pages

src/dataloader.ts
Fixes https://github.com/duckdb/duckdb/issues/10849.
Test data loader:
```sh
duckdb :memory: <<EOF
copy (select * from range(10) tbl(i)) to '/dev/stdout' (format parquet, codec zstd)
EOF
```
=> fix spawn stdout

examples/loader-duckdb/src/index.md
Not sure if there was an intention to change bar to rect? Feels more natural to use a bar here (it results in the same chart anyway.)
Order x, y.
=> duckdb nits

src/deploy.ts, src/observableApiClient.ts
#1340 logs the contents of the new build manifest
=> Use clack.log, and a smaller message

src/deploy.ts
The `deployPollInterval` was set to zero, but the `deploy` command wasn’t respecting this due to a logical error (`||`). Also, the `deployPollInterval` needs to be passed through to the `loginInner` method’s `pollTime` option to avoid polling there, too. If desired, we could make this latter polling interval a separate option for the deploy command, but it seems reasonable to have the same option apply to both. (And maybe in the future we could avoid polling entirely with server-sent events or some such?)
On my computer, this makes the tests take 4.9 seconds, down from 15.5 seconds.
=> no poll delay for deploy tests

test/deploy-test.ts
While reviewing #1399, I was surprised the test hit used `loginInner` at all, because it wasn't testing the login flow. I changed the tests to start with an API key, instead of needing to pretend to get one from logging in.
This won't change what the test is testing or it's speed much, but it makes it a smaller, more focused test that only works on what it says it is doing.
=> Don't use the login flow for tests that aren't testing login

src/client/search.js
This allows the Mod-Enter keyboard shortcut to open search results in a new tab, making it much easier browse through the results (without needing to restore the search query as in #897 — though we could still do that) as long as you don’t mind having more than one tab open.
=> mod-enter to open in new tab

README.md
`README.md` currently links to `./CONTRIBUTING.md` which does not exist. This updates the link to `./docs/contributing.md`.
=> Fix for broken link to CONTRIBUTING.md

examples/plot/src/index.md
The Plot dashboard assumed that it was being built every day, but since we stopped building it, it was (arguably correctly) showing a gap in the latest data. Since we no longer build it every day, it’s more appropriate to show it as a point-in-time snapshot, and hence the `end` should be computed from the data rather than based on the current time.
https://observablehq.observablehq.cloud/framework-example-plot/
Before:
After:
=> determine end from data

src/client/main.js
Fixes #1430. We were forgetting to clear old content when a cell is undefined during preview.
=> clear old content on undefine

templates/default/src/index.md.tmpl
Applies a bit of padding (in addition to margin) so the background extends below the descenders. Also moves the styles to the end of the `index.md` so that it’s a bit friendlier to edit the example `index.md` (without getting distracted by some elaborate CSS).
Before:
After:
=> fix descender clip

src/client/inspect.js
The inspector replaces its contents when objects are expanded; this prevents `display` from being able to cleanup. To fix this, we retain the wrapper DIV element around the inspector contents. Fixes #1456.
=> fix inspector cleanup

examples/README.md, examples/loader-rust-to-json/.gitignore, examples/loader-rust-to-json/README.md, examples/loader-rust-to-json/observablehq.config.js, examples/loader-rust-to-json/package.json, examples/loader-rust-to-json/src/.gitignore, examples/loader-rust-to-json/src/data/poker-ts.json.ts, examples/loader-rust-to-json/src/data/poker.json.rs, examples/loader-rust-to-json/src/index.md
For our recent data loaders, I had prepared two examples, but only had time to demo one of them in the presentation. This is the other one, a data loader example that uses Rust to simulate 10 million poker hands and reports the probability of getting each hand.
=> rust data loader example

docs/loaders.md, examples/loader-python-to-csv/src/index.md, examples/loader-python-to-png/src/index.md, examples/loader-python-to-zip/src/data/earthquakes.zip.py, examples/loader-python-to-zip/src/index.md
This consolidates the recommendation on using a Python virtual environment to the [Data loaders: Execution](https://observablehq.com/framework/loaders#execution) page. In addition, it avoids using `$` when demonstrating commands so that the code can be copied using the copy button and pasted into the terminal without editing.
The virtual environment documentation is now also slightly expanded to cover both venv and uv:
Before:
After:
=> consolidate venv docs

src/deploy.ts
Cobus pointed out that the `@workspace/slug` format we were using looks a lot like our Notebook URLs, and can lead people to 404s if they try to naively create a URL from it. Breaking up the information like this helps make it not look like a URL. I'm open to other formats though, including not making the change if you want to debate it with Cobus.
=> tweak format of project identifiers in deploy

src/convert.ts, src/create.ts, src/deploy.ts, src/observableApiAuth.ts, src/tty.ts, test/tty-test.ts
closes #1447
closes #1446
~~I'm not happy that I had to make c8 specifically ignore the non-coverage of the non-tty output tests, but I did not find a better way.~~ (solved in the new approach, see below)
=> if stdout is not a tty, replace clack.spinner by console.log

examples/README.md, examples/loader-census/.gitignore, examples/loader-census/README.md, examples/loader-census/observablehq.config.js, examples/loader-census/package.json, examples/loader-census/src/.gitignore, examples/loader-census/src/data/ca.json.sh, examples/loader-census/src/index.md
deployed at https://observablehq.observablehq.cloud/framework-example-loader-census/
Note: this example slightly differs from the original https://mbostock.observablehq.cloud/framework-help/2024-05-01-census-boundaries/ in that:
* it uses a `.sh` extension instead of a `.exe` extension
* it uses topojson.mesh to draw the counties borders
Using the `.sh` extension makes it simpler (no `+x` bit) but forces a small modification of the script: for some reason the construction with `<(script)` doesn't seem to be compatible with the way we invoke shell scripts. Maybe it's `sh` vs. `bash`?
=> US Census Bureau shapefiles example

examples/loader-python-to-csv/src/index.md
The python code uses `pandas` and not `geopandas`.
=> fix wrong library mention

templates/default/src/index.md.tmpl
=> Update link to responsive display

src/client/sidebar.js
This small enhancement makes it so that when the sidebar is opened in floating mode (with a drop shadow), Escape will close the sidebar in the same fashion as clicking on the backdrop. (Note that this sidebar can either be opened persistently with Command-B, or temporarily opened with Command-K.)
=> close floating sidebar on escape

docs/jsx.md
I spent some time trying to understand why the simpler JSX example wasn't working in my project. It finally turned out that I was putting the `display(<Greeting subject="JSX" />)` in a `js` block instead of a `jsx` one.
I saw after that `jsx` is indicated in the right margin of the code block in the documentation, but I didn't notice at first. As I may not be the only one in this case, this PR explicitly shows the `jsx` fenced code block around the first JSX `display()`.
Many thanks for all your work on Observable framework.
=> Explicitly show that JSX display() must be in a jsx fenced code block

src/javascript/imports.ts
I noticed a small bug in preview, which is that `modulepreload` links weren’t being generated for local components. That was because the `isJavaScript` test was failing due to the trailing `?sha=…`.
=> fix modulepreload in preview

docs/inputs/table.md, package.json, src/client/stdlib/inputs.css, src/rollup.ts, yarn.lock
Ref. https://github.com/observablehq/inputs/releases/tag/v0.11.0
We still need to bake-in Inputs for two reasons: we define `Inputs.file` using our implementation of `AbstractFile`, and we modify the stylesheet to use theme variables. Fixes `file.type` and `file.lastModified` when using `Inputs.file`.
=> @observablehq/inputs 0.11

package.json, src/deploy.ts, src/markdown.ts, src/slugify.ts, test/output/build/config/closed/page.html, test/output/build/config/toc-override.html, test/output/build/config/toc.html, test/output/build/pager/sub/page1..10.html, test/output/hello-world.html, test/output/setext.html, test/output/tex-expression.html, test/slugify-test.ts, yarn.lock
=> adopt @sindresorhus/slugify

.github/workflows/deploy.yml, docs/.observablehq/deploy.json, docs/deploying.md, examples/observablehq.config.js, observablehq.config.ts
Switches Framework’s docs to be hosted on Observable Cloud instead of Cloudflare Pages.
=> deploy to observable

docs/getting-started.md, docs/index.md
By using `npx` directly, we can specify the latest version of Framework (rather than whatever was cached the first time you run `npm init`). Also it makes it more obvious which package is being run. It is slightly longer though, and there’s no yarn equivalent (but you can still pick Yarn when installing via `npx` if you want).
=> recommend npx

docs/index.md
I just realized that the title was much larger than on the home page, and resulted in poor alignment
| - | - |
| ![before](https://github.com/user-attachments/assets/a9a27a7b-2312-4314-9f12-bd1b8874986c) | ![after](https://github.com/user-attachments/assets/8c8e7791-cf18-4cc0-95a7-6a9c44bee65a) |
=> fix hero title

docs/index.md, docs/style.css
This…
* Uses normal font-weight instead of 500 for body text (preference)
* Adopts phosphate as the focus color instead of blue (to reduce the number of accent colors)
* Adopts phosphate as the CTA color for “Get started” on the home page (ditto)
* Adopts Inter as the sans-serif font instead of San Francisco (to reduce the number of fonts)
* Adopts Spline Sans Mono as the monospace font for code instead of Menlo (ditto)
* Tweaks the font-size for code and tt elements to inherit (due to the above changes)
|---|---|
| <img width="1624" alt="Screenshot 2024-08-20 at 8 58 37 PM" src="https://github.com/user-attachments/assets/df092bff-1d32-4c31-8083-ddc53970eca7"> | <img width="1624" alt="Screenshot 2024-08-20 at 8 58 27 PM" …
=> design tweaks

docs/javascript.md, docs/reactivity.md, docs/style.css
Fixes #1584, with a simplified and monochromatic approach. Fixes the font size of code within heading elements (which should inherit the heading font size, as we now do for code within prose). Also restores default top margins for heading elements (personal preference). Also fixes some anchor links broken by #1562.
|---|---|
| <img width="1624" alt="Screenshot 2024-08-21 at 6 41 26 AM" src="https://github.com/user-attachments/assets/530b462d-aa7e-4a79-b745-dfd15071f471"> | <img width="1624" alt="Screenshot 2024-08-21 at 6 41 18 AM" src="https://github.com/user-attachments/assets/6ea63b55-5b65-43a5-8bb9-3bdcc5a87e08"> |
| <img width="1624" alt="Screenshot 2024-08-21 at 6 41 50 AM" src="https://github.com/user-attachments/assets/27795bd9-3d70-41c9-a9bb-a5f9c80dd6bf"> | …
=> more design tweaks

docs/css/card.md, docs/css/color.md, docs/css/grid.md, docs/css/note.md, docs/javascript/display.md, docs/javascript/files.md, docs/javascript/generators.md, docs/javascript/imports.md, docs/javascript/inputs.md, docs/javascript/mutables.md, docs/javascript/promises.md, docs/javascript/reactivity.md, docs/routing.md
I’ve implemented these redirects through Cloudflare, so we no longer need (or want) client-side redirects. You can test these redirects to confirm:
https://observablehq.com/framework/css/card
https://observablehq.com/framework/css/color
https://observablehq.com/framework/css/grid
https://observablehq.com/framework/css/note
https://observablehq.com/framework/javascript/display
https://observablehq.com/framework/javascript/files
https://observablehq.com/framework/javascript/generators
https://observablehq.com/framework/javascript/imports
https://observablehq.com/framework/javascript/inputs
https://observablehq.com/framework/javascript/mutables
https://observablehq.com/framework/javascript/promises
https://observablehq.com/framework/javascript/reactivity …
=> remove redirects

docs/lib/generators.md, docs/themes.md.ts
| -- | -- |
| ![before](https://github.com/user-attachments/assets/6fe8cddd-4b4a-43d4-a77f-3bfb94e36bbd) | ![after](https://github.com/user-attachments/assets/e231d477-fcec-4da6-94de-7b59b8f11e6b) |
=> when we search "dark" or "width" we want these pages on top

examples/datawrapper-api/src/index.md
This…
* Adopts Datawrapper’s recommended embed script code for simplicity
* Favors static rendering of the embed script for better performance
* Uses `data-dark="auto"` likewise for performance and simplicity
=> static Datawrapper embed code

docs/theme/[theme].md.ts
Fixes #1615. Maybe not the best fix since this still loads Inter and Spline Sans Mono even though they are unused. That’s because the **globalStylesheets** option applies to the theme previews even though they don’t use our custom stylesheet. Maybe we should have a **stylesheets** front matter option that allows us to override the global stylesheets from the config, so we can restore it back to the default here?
=> restore Source Serif 4 for theme previews

docs/telemetry.md, src/telemetry.ts
I was reviewing the [telemetry documentation](https://observablehq.com/framework/telemetry) and noticed we forgot to update it for #1604, and that the declared `TelemetryEnvironment` wasn’t being enforced (because TypeScript allows you to return objects with excess properties). By instead declaring the returned type as a local variable, we can get TypeScript to enforce that the object literal has only the declared properties we intend. I also added a few more type declarations for extra safety.
=> document userAgent telemetry

src/client/stdlib/duckdb.js
=> use CREATE TABLE for small parquet

observablehq.config.ts, src/config.ts, src/loader.ts, src/pager.ts, test/output/build/archives.posix/tar.html, test/output/build/archives.win32/tar.html, test/output/build/fetches/foo.html, test/output/build/files/files.html, test/output/build/imports/script.html, test/output/build/search-public/page1.html, test/output/build/simple/simple.html, test/pager-test.ts
If a page is listed in the **pages** config option, we should build it even if it’s not listed in **dynamicPaths**. Also, we shouldn’t build a page more than once.
=> include pages in default paths

src/loader.ts, src/route.ts, test/route-test.ts
Fixes #1629. Allows empty extensions for static files (and correctly returns a 404 during preview); they’re still not allowed for data loaders, nor recommended.
=> handle empty extensions

docs/imports.md, docs/javascript.md, docs/jsx.md, src/javascript/module.ts, src/loader.ts, src/markdown.ts, test/input/build/typescript/index.md, test/input/build/typescript/sum.ts, test/output/build/typescript/_import/sum.fd55756b.js, test/output/build/typescript/index.html
Reboot of #129. Fixes #79.
TODO
Unlike #129, I expressly avoided allowing TypeScript in inline expressions, which allows us to avoid running the esbuild transform on them, and in turn avoids the problem of esbuild converting expressions to expression statements and then losing implicit display. Not also that there is no implicit display in <code>```ts</code> blocks. I think this is an acceptable tradeoff, at least for now, as you get the primary benefits of TypeScript modules and TypeScript fenced code blocks and only if you explicitly opt-in to using TypeScript.
Also unlike #129, this only allows TypeScript to be imported with the `.js`, as we do for `.jsx`. This is the recommended practice because it means the import path doesn’t change after transpilation.
=> TypeScript

src/render.ts, src/resolvers.ts
=> detect non-local sql tables

docs/telemetry.md
The ts code block wasn't displaying on the telemetry documentation.
Before
After
=> Visible telemetry data types

docs/files.md
=> Add version badge to docs referencing file.size

examples/eia/src/components/charts.js, examples/eia/src/components/map.js, examples/eia/src/index.md
This was a transient warning, due to the fact that the charts run independently. The height of the interchange chart was negative when the map had not yet been inserted in the DOM. By setting a min-height in css, we avoid the warning and more importantly only compute the charts once.
Thanks @mootari for reporting.
In addition, I fixed the display for small screens.
redeployed at https://observablehq.observablehq.cloud/framework-example-eia/
=> fix responsive chart dimensions on the EIA example

src/deploy.ts
The server uses `failed` when the deploy fails, not `error`. Also, we should handle the `canceled` status. Any other status should be considered unexpected. Fixes https://github.com/observablehq/observablehq/issues/18081.
=> fix error on failed deploy

docs/data-loaders.md, docs/data/dft-road-collisions.csv.sh, docs/quakes.json.sh, examples/eia/src/data/eia-system-points.json.sh, examples/loader-census/src/data/ca.json.sh, examples/loader-census/src/index.md, examples/loader-duckdb/src/educ_uoe_lang01.parquet.sh, examples/loader-duckdb/src/index.md
`curl` is a rare unix utility that does not return an error code > 0 when it fails, unless we use [`-f`](https://curl.se/docs/manpage.html#-f) (`--fail`); seems like a best practice we should promote.
=> adopt curl -f to make the data loader fail if curl fails to download

docs/style.css, src/style/global.css, src/style/layout.css
(e.g. https://observablehq.com/framework/files#static-analysis)
Now also fixes #1686.
=> fix scroll margin for anchor links; fix conditional header layout

package.json, yarn.lock
The version of send 0.0.18 has a published vulnerability that is fixed in 0.0.19, see https://github.com/advisories/GHSA-m6fv-jmcg-4jfg. However, the version specifier of "^0.0.18" in package.json does not allow projects to use 0.0.19.
This changes the specifier to "^0.0.19" which allows (and requires) Observable Framework projects to use 0.0.19 to avoid the vulnerability.
Note that the vulnerability https://github.com/advisories/GHSA-m6fv-jmcg-4jfg has been public for over 2 weeks at this point, and so this isn't disclosing anything new.
=> Increase the required version of send from 0.0.18 to 0.0.19

src/deploy.ts
Fixes #1678. Taking advantage of Sweden using ISO 8601 as their preferred date format… which is a hack, but very convenient assuming it continues to work? 🤷
=> use ISO date

src/build.ts, src/deploy.ts, src/observableApiClient.ts, test/build-test.ts, test/deploy-test.ts, test/mocks/observableApi.ts
This uses recent updates to the server protocol to update project titles. This approach is simpler for the client, and moves more of the stateful logic to the server that has more information.
=> Update title via postDeployUploaded instead of postUpdateProject

src/client/sidebar-init.ts
This reverts commit fca687cf98ce88815a654ba24c06e7a785f7a063. I think this was a holdover from when we used basic auth for the beta documentation. We shouldn’t need this now.
=> Revert "fix auth-in-url (#576)"

src/sql.ts, test/sql-test.ts
Removes the selection column UI on the displayed result of a `sql` code block, since this interaction is not operational.
In the case of a named block, we could imagine reenabling it if it would drive changes to the values passed to id; but it's not the case at the moment (and I'm not sure it would be the best UX anyway).
=> removes the selection UI on sql code block displays

docs/sql.md
I see this bug in the last chart of https://observablehq.com/framework/sql
this spurious rect corresponds to datum 34 which has mag1 = mag2 = null. Plot does not handle correctly the `null`s in arrow vectors.
<del>It's still unclear to me why it does not happen all the time, and why it happens at all.</del>
=> bug in sql.md: fix the query to ignore nulls

src/build.ts, test/input/build/imports/foo/foo.js, test/javascript/module-test.ts, test/mocks/jsdelivr.ts, test/output/build/imports/_import/bar/bar.13bb8056.js, test/output/build/imports/_import/bar/bar.4460ccc2.js, test/output/build/imports/_import/bar/baz.2add1dd0.js, test/output/build/imports/_import/foo/foo.bcd720b2.js, test/output/build/imports/_npm/@example/url-import@1.0.0/1dd108c5.js, test/output/build/imports/foo/foo.html
Fixes #1755. ~~I’d like a test here, but I think it would require us to mock out the contents of jsDelivr responses. I tested manually using the repro in the linked issue.~~ Added an automated test, easy enough.
=> handle absolute global imports

package.json, src/commandInstruction.ts, src/tty.ts, yarn.lock
Replaces our hand-rolled version with the popular [picocolors](https://github.com/alexeyraspopov/picocolors), offering support for `NO_COLOR` and relying on picocolor’s own color support detection. As an alternative, we could also use [yoctocolors](https://github.com/sindresorhus/yoctocolors) which already uses [`hasColors`](https://nodejs.org/api/tty.html#writestreamhascolorscount-env)… but I figured picocolors is nice because it’s already a dependency of clack.
Related #1764.
=> adopt picocolors

templates/default/README.md.tmpl, templates/empty/README.md.tmpl
Fixes #1783. Also updates some redirected links.
=> mention install in template README

docs/config.md, docs/getting-started.md, src/config.ts, src/preview.ts, templates/default/observablehq.config.js.tmpl, templates/empty/observablehq.config.js.tmpl, test/config-test.ts
Fixes #1781. Replaces the **cleanUrls** option with separate **preserveIndex** and **preserveExtension** options.
=> preserveIndex, preserveExtension

src/style/layout.css
=> sidebar atop header

src/files.ts, src/path.ts, test/path-test.ts
Ref. https://github.com/observablehq/framework/discussions/1792
=> fix within on Windows

docs/embeds.md
Adds one sentence at the top and one tip replacing the previous "Coming soon" callout. (Supersedes https://github.com/observablehq/framework/pull/1830, in which I branched off the wrong branch!)
Before|After
-|-
=> Edit documentation to cite Observable Cloud support for embedding

src/npm.ts
Alternative to #1870. Fixes #1866.
It sounds like you tried this already (“I'm trying to see if we can reroute "npm:react-dom" to "npm:react-dom/client" for asc. compat. (NO)”) but it works for me?
=> use /client for react-dom

src/libraries.ts, test/libraries-test.ts
Fixes #1907.
Fixes a regression in #1759 where an implicit download (via fetch) was promoted to an implicit dependencies (via import).
=> fix sqlite implicit dependencies
