observablehq/framework

- docs/getting-started.md
> windows tip

- docs/javascript/files.md
- src/client/stdlib/fileAttachment.js
> absolute FileAttachment.url

- docs/theme/generate-themes.ts
This turns off analytics for the theme preview pages.
> no theme head

- src/markdown.ts
> {html,svg}.fragment

- examples/api/observablehq.config.ts
- examples/chess/observablehq.config.ts
- examples/eia/observablehq.config.ts
- examples/google-analytics/observablehq.config.ts
- examples/hello-world/observablehq.config.ts
- examples/mortgage-rates/observablehq.config.ts
- examples/penguin-classification/observablehq.config.ts
- examples/plot/observablehq.config.ts
- observablehq.config.ts
> disable local analytics

- src/build.ts
> only rollup js

- src/convert.ts
> consistent convert logs

- docs/config.md
- src/config.ts
- src/markdown.ts
- src/preview.ts
- test/config-test.ts
> markdown-it plugins

- .eslintignore
- .github/workflows/deploy.yml
- .gitignore
- docs/contributing.md
- examples/api/package.json
- examples/chess/package.json
- examples/eia/package.json
- examples/google-analytics/package.json
- examples/hello-world/package.json
- examples/mortgage-rates/package.json
- examples/penguin-classification/package.json
- examples/plot/package.json
- observablehq.config.ts
- package.json
- test/files-test.ts
- tsconfig.json
This…
- moves `dist/` to `docs/.observablehq/dist/`
- moves `build/` to `dist/`
- moves `build.test/` to `test/build/`
> dist shuffle

- docs/getting-started.md
> remove cautionary note about windows

- src/render.ts
- src/resolvers.ts
Fixes preloading of transitive static imports. Also fixes duplicate preloads.
> fix transitive preloads

- docs/markdown.md
Pretty sure an entry for sql is needed, but not sure how it should read
> Add skeleton of sql item

- src/client/preview.js
#844 had the unfortunate behavior that DuckDB is loaded even if it’s not used because we might need to call `registerTable`. Now we load DuckDB lazily only when we need to call `registerTable`.
Fortunately this only affects preview and not build! 😬
> lazily load DuckDB during preview

- src/build.ts
- test/output/build/imports/script.html
Fixes https://github.com/observablehq/framework/pull/1035#pullrequestreview-1938279810.
> fix resolveScript during build

- docs/deploying.md
Various copy edits, but probably most importantly, more detail on the specific steps needed to create an Observable API key and GitHub secret.
> deploy edits

- docs/loaders.md
Downloads the world-atlas data from npm for self-hosting. 🎉
> npm:world-atlas

- src/client/preview.js
> automatic reconnect

- src/rollup.ts
> more precise esbuild target

- src/preview.ts
> fix infinite normalize loop

- src/npm.ts
Fixes a (theoretical) bug where the cache could collide if you change the **root** option in the config.
> fix npm cache collision

- docs/lib/jquery-ui.md
- src/npm.ts
Alternative to #1177 that makes jquery-ui a little bit easier to use, and is minimal effort for us.
> minimal jquery-ui support

- src/npm.ts
- test/npm-test.ts
> revert implicit /+esm for .js

- src/client/main.js
Fixes #1206. I tested with the following page:
````md
```js echo
const a = Promise.resolve(1);
```
```js echo
const b = new Promise((resolve) => setTimeout(() => resolve(2), 2000));
```
```js echo
a + b;
```
${a + b}
````
Which I manually edited to:
````md
```js echo
const a = Promise.reject(1);
```
```js echo
const b = new Promise((resolve) => setTimeout(() => resolve(2), 1000));
```
```js echo
a + b;
```
${a + b}
````
If you toggle back and forth between the two states you can reproduce the bug and confirm the fix.
> reset after rejection

- docs/config.md
(based on user feedback that this is not immediately obvious)
> clarify how you install a markdownIt plugin

- src/node.ts
- src/npm.ts
- src/resolvers.ts
- test/javascript/transpile-test.ts
Fixes #1224. Easy fix. We just forgot to resolve them. 🤦 Added a test!
> fix node imports

- src/deploy.ts
- test/deploy-test.ts
> Handle created deploy status, in case deploy hasn't yet updated to pending.

- src/preview.ts
> normalize page paths in preview

- src/bin/observable.ts
- src/deploy.ts
- src/format.ts
- src/observableApiClient.ts
- test/deploy-test.ts
- test/format-test.ts
- **Provide more errors when failing to upload a file**
- **Add pre-deploy check for large files**
> better messaging when deploying large files

- src/client/stdlib/fileAttachment.js
- src/preview.ts
> populate lastModified on update

- docs/files.md
per https://talk.observablehq.com/t/how-to-resolve-promise-after-loading-large-fileattachment-in-observable-framework/9240/5
> remove dead link

- docs/getting-started.md
For the first part I haven't put in the yarn equivalent, to keep it light. But maybe it's better to be complete?
> document npm update

- src/client/stdlib/resize.ts
> async resize

- docs/style.css
- src/render.ts
Followup to #1306 which allowed external links in the sidebar.
> ↗︎ for external sidebar links

- examples/README.md
- examples/geotiff/README.md
- examples/google-analytics/README.md
- examples/hello-world/README.md
- examples/netcdf/README.md
- examples/plot/README.md
- examples/responsive-iframe/.gitignore
- examples/responsive-iframe/README.md
- examples/responsive-iframe/observablehq.config.js
- examples/responsive-iframe/package.json
- examples/responsive-iframe/src/.gitignore
- examples/responsive-iframe/src/embed.md
- examples/responsive-iframe/src/index.md
- src/config.ts
https://observablehq.observablehq.cloud/framework-example-responsive-iframe/
> responsive-iframe example

- test/input/build/pager/null.md
- test/output/build/pager/null.html
> test pager false

- docs/config.md
- src/config.ts
- src/pager.ts
- src/render.ts
- src/search.ts
- src/style/layout.css
- test/config-test.ts
- test/input/build/pager/observablehq.config.js
- test/output/build/pager/index.html
- test/output/build/pager/sub/index.html
- test/output/build/pager/sub/page0.html
- test/output/build/pager/sub/page1..10.html
- test/output/build/pager/sub/page1.html
- test/output/build/pager/sub/page2.html
- test/output/build/pager/sub/page3.html
- test/output/build/pager/sub/page4.html
- test/output/build/pager/sub/page5.html
- test/output/build/pager/sub/page6.html
- test/output/build/pager/sub/page7.html
- test/output/build/pager/sub/page8.html
- test/pager-test.ts
> section links

- examples/README.md
- examples/codemirror/.gitignore
- examples/codemirror/README.md
- examples/codemirror/observablehq.config.js
- examples/codemirror/package.json
- examples/codemirror/src/.gitignore
- examples/codemirror/src/components/Editor.js
- examples/codemirror/src/index.md
https://observablehq.observablehq.cloud/framework-example-codemirror/
> codemirror example

- src/client/stdlib/fileAttachment.js
- test/client/stdlib/fileAttachment-test.ts
> canonical FileAttachment

- src/deploy.ts
- test/deploy-test.ts
> Don't prompt for interactive login on non-interactive terminals

- examples/loader-airtable/src/data/penguins.csv.ts
(https://github.com/observablehq/framework/pull/1477#pullrequestreview-2142121764)
> non-null type assertion

- docs/sample-datasets.md
The page is indexed but not listed — the goal is that when someone searches for "penguins" they can find the provenance.
closes #817
> document sample datasets

- docs/lib/dot.md
> document Viz.js

- docs/index.md
- docs/style.css
- observablehq.config.ts
As per design's guidelines.
- Spline Sans Mono for the h1 headers
- Inter 16px for the body text, line-height of 1.5
- Font weight 500 for both
- Dark mode font color changed to #FEFEFE
> Documentation font changes

- docs/lib/generators.md
https://github.com/observablehq/framework/blob/main/src/client/stdlib/generators/dark.ts
https://github.com/observablehq/framework/blob/main/src/client/stdlib/generators/width.ts
> fix links: js -> ts

- src/deploy.ts
> use maxItems for unbounded select

- src/config.ts
- src/files.ts
- src/loader.ts
- src/route.ts
- test/build-test.ts
- test/files-test.ts
- test/input/build/page-loaders/hello-js.md.js
- test/input/build/page-loaders/hello-ts.md.ts
- test/input/build/page-loaders/index.md.sh
- test/loader-test.ts
- test/output/build/page-loaders/hello-js.html
- test/output/build/page-loaders/hello-ts.html
- test/output/build/page-loaders/index.html
- test/route-test.ts
Fixes #1624. Though in my opinion that issue should be broken into several issues: this PR finds non-parameterized page loaders, but we might still want the ability to crawl links to find parameterized pages, and we might also want to include page loaders and parameterized pages in the default sidebar. But I don’t plan on working on these issues currently.
> find non-parameterized page loaders, too

- src/build.ts
> no-clobber redux

- src/create.ts
> better create into cwd

- src/render.ts
> deduplicate resolved imports

- src/route.ts
- test/route-test.ts
> a parameterized route can map [foo] onto itself

- docs/lib/duckdb.md
cheat a little to make the output of FROM duckdb_extensions() more interesting
|--|--|
| <img width="839" alt="Capture d’écran 2024-11-02 à 13 07 28" src="https://github.com/user-attachments/assets/5ed4aa1c-8b6f-4c2d-9a25-53a88bdbd477"> | <img width="832" alt="Capture d’écran 2024-11-02 à 13 07 19" src="https://github.com/user-attachments/assets/a9550787-9d7c-4ee9-aa57-e767bdfb8741"> |
> show 1 extension

- docs/telemetry.md.js
> index the telemetry page
